Bump dependency and AGP versions
android/databinding-samples pull request #49
Opened 2023-01-18 13:21 UTC by tunjid

2023-01-30 14:03 UTC, ARCHANA-KUMARI approved these changes

2023-02-01 09:43 UTC, JoseAlcerreca requested changes
Whenever you update gradle, you need to update the wrapper!

2023-02-03 13:23 UTC, tunjid commented
> 

I did in gradle.properties, I bumped to 7.5: `distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip`

2023-02-06 11:42 UTC, JoseAlcerreca approved these changes

2023-02-06 11:52 UTC, merged